name: cdk

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::977099026169:role/GitHubActionsRole
          aws-region: ap-northeast-1
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'
      
      - name: Setup dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test

      - name: CDK Diff Check
        run: npm run cdk

      - name: CDK Deploy
        run: npx cdk deploy --require-approval never --all